# -------------------------------
# Application Settings
# -------------------------------
spring.application.name=finora-2026-spring
server.port=${PORT:8080}
spring.config.import=optional:file:.env[.properties]

# -------------------------------
# PostgreSQL Database Configuration
# -------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------
# Hibernate / JPA Settings
# -------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# -------------------------------
# HikariCP Connection Pool Settings
# -------------------------------
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.validation-timeout=5000

# -------------------------------
# MongoDB setting
# -------------------------------
spring.mongodb.uri=${DB_URL_MONGO}
spring.mongodb.database=${DB_DATABASE_MONGO}